### ISSUE TITLE
When initialing a project,you must use https protocol to push so that the webui will update.

### ISSUE THREAD

**Issue by wicast** [gogits/gogs#1864]
The problem is strange……I am using a cubieboard as my gogs server host.
These commit push with ssh is not lost,but these commits didn't make the webui update until you use https protocol to push once.Everything back to normal.

**Comment by wicast** [comment]
And here is  some more information,the problem only occurs when the repository is started emptily.

**Comment by Unknwon** [comment]
> These commit push with ssh is not lost,but these commits didn't make the webui update

This mean you did not add a SSH key in a Gogs way. Can you give details on this?

**Comment by Unknwon** [comment]
PS: see comment https://github.com/gogits/gogs/issues/1576#issuecomment-137675306

**Comment by wicast** [comment]
I'm pretty sure I had already added my ssh public key.
The problem is,if you create a totally empty repo,the web contents won't update even you have upload a lot of things with ssh protocol.
To solve/avoid this problem, you can upload via http once,so that the repo  webui can be update by ssh.
And another method is you can init with some README file etc.Then there were no problems.

**Comment by Unknwon** [comment]
> I'm pretty sure I had already added my ssh public key.

What is the step you add and what is the SSH url you push to?

**Comment by wicast** [comment]
SSH public key was add via webui of gogs,and it was in my /home/gogs/.ssh/authorized_keys.
For instance,the name is "test",and "alarm" is my host name
```
$ git remote show origin
* 远程 origin
  获取地址：gogs@alarm:wicast/test.git
  推送地址：gogs@alarm:wicast/test.git
  HEAD 分支：(unknown)
  为 'git pull' 配置的本地分支：
    master 与远程 master 合并
```

What really confused me is,the push/pull operation is actually edited the files in remote repo,so my commits didn't lost.But I can't see these changes on the webui.

**Comment by wicast** [comment]
I just tried https://try.gogs.io,the problem didn't occurs.I notice that i am using 0.6.15.0926 and the demo website is 0.6.18.1031 Beta

**Comment by Unknwon** [comment]
Can you run following two tasks in admin dashboard:

![image](https://cloud.githubusercontent.com/assets/2946214/10865117/b197d9c6-7fd7-11e5-9ce8-32fc60bc5d0d.png)

Then try again?

**Comment by wicast** [comment]
No……it's not working.

**Comment by Unknwon** [comment]
Can you dump your `/home/gogs/.ssh/authorized_keys` file?

**Comment by wicast** [comment]
```
command="/usr/share/gogs/gogs serv key-3 --config='/srv/gogs/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCopDQu4OgrwJODPfvqKIxgCvpLcUExViu6q5KAuqnfpbZK2fR9U70/edusFs3jcDIC18lfaienaJEJYUjqQNNzP4dGd7+TGrIDt4F0B0zhXYeM5AoHxHAjSJN/CKxDtLL48iKa13t1YhMMPp4m+/VXQ3DsuVzVgMmPFY/u0nVvTN2o3yAwZ5kjj6SzTDEom55SzM6v9Jh8XLJ9RxzW36o7Q+WPXKkzBLZhsTjycFYrawiW+ZTcSnqHfdYkbnt1NR0EqP64ep2+xaG9Dg+kbS/Lu8deFx3eSgGzDYj29pLsuSZsv9stv2sffaPR5kQm66Ru3FLpNS7MznbCmZCiN1HF eb:e2:bc:1a:d4:a3:6d:8c:d8:a7:30:2d:d3:20:b5:f6 cubie
```

**Comment by Unknwon** [comment]
Thanks, can you dump `path/to/repo_root_path/wicast/test.git/hooks/update` file?

**Comment by wicast** [comment]
#!/usr/bin/env bash
"/usr/share/gogs/gogs" update $1 $2 $3 --config='/srv/gogs/conf/app.ini'

every update file is the same.

**Comment by Unknwon** [comment]
I'm running out of ideas....

**Comment by wicast** [comment]
Later I will take a try with 0.6.18(

**Comment by Unknwon** [comment]
Version does not matter... the code was written months ago...

But, I found something may resolve this. Just want to make sure, after you through SSH, do you see news feed like `xx pushed to xxx` in your dashboard (for non-organization repositories)?

**Comment by wicast** [comment]
No,same as repo's ui.Only the init info of the repo.

**Comment by wicast** [comment]
And I found that all my repo that update with ssh won't show the news feed either even the repo ui is working fine.

**Comment by Unknwon** [comment]
Can you take a look at `path/to/gogs/log/serv.log` and `path/to/gogs/log/update.log` see if any errors there?

**Comment by wicast** [comment]
gogs.log http://pastebin.com/3Sjt1f33
xorm.log http://pastebin.com/JjSGmSa8
other two file http.log and serv.log is empty

**Comment by Unknwon** [comment]
How about `path/to/gogs/log/update.log`?

**Comment by Unknwon** [comment]
Can you check database table `update_task` see if any records there?

**Comment by wicast** [comment]
http://pastebin.com/kNWQZy8c
i was using sqlite3 and the table was empty

**Comment by Unknwon** [comment]
Thanks.

So if table is empty and no news feed is generated, I think the update hook is never been called. But I don't know why...

**Comment by JohnMaguire** [comment]
Should @wicast check for existence of the hook? Alternatively he could add logging to the hook to see if that is being called with HTTPS but not SSH. Definitely extremely odd.

**Comment by Unknwon** [comment]
Any updates?

**Comment by wicast** [comment]
It seems no change at all even with the latest version.I have tried  exactly same setup(sqlite 3.9.2,linux 4.3,go 1.5.1,gcc 5.2.0 and same buildscript from [aur](https://aur.archlinux.org/packages/gogs/)) on my x86_64 laptop,the result is ok.
So I really feel that  the problem was probable caused by ARM,but I don't have any other board on hand.
And I'm not too sure how to log these hooks correctly.

**Comment by Unknwon** [comment]
@wicast when latest release (0.7.22), you can use builtin SSH server, maybe that would help?

**Comment by fanningert** [comment]
@wicast: The AUR package is working correctly on a ARM (like RPi 1 and 2) with the current version 0.7.22 (My installation is running on a RPi2). For me, it was not possible to use the OS SSH server for git commands over SSH. But with the internal SSH server of Gogs, it is working perfectly. Only a little bug in the internal SSH-Server (#1681), but in the current develop branch the bug is corrected (ca96e04). 

I will test your scenario (like you wrote some blocks up) on my system (RPi2) with the current release (0.7.22). <- tomorrow

**Comment by wicast** [comment]
I have bumped to the dev version but nothing changed here even with buildin-ssh.But a strange thing happened to my xorm.log that after I push something via git(webui still not changed),there is a huge empty line fill with U+0000.Something must happened there.

.
[xorm.log.txt](https://github.com/gogits/gogs/files/48480/xorm.log.txt)

**Comment by Unknwon** [comment]
@wicast what is the URL you use to push through SSH?

**Comment by wicast** [comment]
gogs@alarm:wicast/test.git
and ssh:// is the same result.

**Comment by Unknwon** [comment]
Looks right. Still having no idea...

**Comment by Unknwon** [comment]
@wicast Here again, any updates? Maybe more logs now available in `serv.log`?

**Comment by wicast** [comment]
Nope,the `serv.log` is nearly empty.
```
2015/12/01 19:46:45 [T] No update task is presented: 7ada0578-bd8b-4896-a43f-316552586d18
2015/12/01 19:58:20 [T] No update task is presented: 14723284-5ed3-4370-b3a5-611ddeb6da18
2015/12/01 20:01:41 [T] No update task is presented: 6a6c7d5d-518d-4161-a82e-a9967d066851
2015/12/06 20:01:46 [T] No update task is presented: 1ffdeb55-23e7-441b-a229-86863cdbc5f0
2015/12/06 20:03:20 [T] No update task is presented: 7623bb2a-9d70-493a-8ff5-166bae86be71
```

should I change the log level?I'm using the default  value `Trace`.

**Comment by Unknwon** [comment]
The log shows `update` command was not successful somehow. Can you check `update.log`?

**Comment by wicast** [comment]
It seems we've found something,but my `/var/log/gogs` folder didn't contain a `uodate.log`.

**Comment by Unknwon** [comment]
..... I think the update hook is really not been called for some reasons.

**Comment by wicast** [comment]
How can log it?

**Comment by Unknwon** [comment]
There is no way... it is called by git.

**Comment by wicast** [comment]
Can I manually  run the hook script?

**Comment by Unknwon** [comment]
Yes, as long as you pass the correct parameters...

**Comment by wicast** [comment]
So how can I get these parameters?

**Comment by Unknwon** [comment]
See https://www.kernel.org/pub/software/scm/git/docs/githooks.html

**Comment by wicast** [comment]
I mean how can I get these `$1 $2 $3`  form gogs

**Comment by Unknwon** [comment]
There are from git, not from Gogs.

**Comment by Unknwon** [comment]
How's going on this?

**Comment by wicast** [comment]
I don't have much time these days, sorry.
I'm considering about using debain to test it if I were free.

**Comment by Unknwon** [comment]
I'll close this one until someone else reports on it.

**Comment by usagirei** [comment]
Sorry to bring up the dead:
But i ran on the same issue using 0.8.25.0129 on a Raspberry PI 2 while testing gogs out (I love it so far btw :+1:)
Pushing via SSH does not update either the feed nor creates the WebUI view
Not a major problem since over HTTP it works, and i mainly connect to the PI over a VPN connection, but it's an issue nonetheless

The SSH Key is being detected as used (it updates the last activity time)
There's no update.log in the logs directory
Already had ran both the rewrite commands

Two test pushes: http://i.imgur.com/YfsoDNp.png
Only the HTTP one shows up in the feed (and creates the WebUI): http://i.imgur.com/OSUoPXW.png

**Comment by Unknwon** [comment]
@usagirei check your `path/to/gogs/log/serv.log` file.

**Comment by usagirei** [comment]
2016/02/16 00:58:25 [T] No update task is presented: 80f6dd5b-c4e4-4e74-938f-730854ad9cf8
2016/02/16 00:59:05 [T] No update task is presented: db1e0ad8-a16e-48e7-8d3d-19586373e2a4
2016/02/16 01:01:58 [T] No update task is presented: 3c510ea9-f3f5-4eac-bd96-ad5cb46c0b8a
2016/02/16 01:02:29 [T] No update task is presented: 754431c6-c749-4302-87e4-fc576ec54250
2016/02/16 01:18:41 [T] No update task is presented: 8803318c-b48f-456e-9f91-df6c472bbce5
2016/02/16 01:18:51 [T] No update task is presented: c86de052-5222-498b-bc3c-dd434df05c07
2016/02/16 01:22:36 [T] No update task is presented: 10cc3d5d-39cd-4132-a6eb-bc424b36aefd

only these lines in

**Comment by Unknwon** [comment]
@usagirei thanks. Are those lines just logged? Please try another time to verify.

**Comment by usagirei** [comment]
correct, just pushed an empty commit after it:

2016/02/16 01:22:36 [T] No update task is presented: 10cc3d5d-39cd-4132-a6eb-bc424b36aefd
2016/02/16 01:30:02 [T] No update task is presented: 8787fac8-cb32-4e6d-9820-4950c74de457 <- new line

**Comment by Unknwon** [comment]
OK, so changes are been made right? (You can verify by web UI)

**Comment by usagirei** [comment]
They are, this one is a test repo i created just now to push stuff, but even without WebUI (since i've only used SSH on this test repo) i can pull it and the files are there, with complete git log

**Comment by Unknwon** [comment]
Now, check your `path/to/gogs/log/update.log` file.

**Comment by usagirei** [comment]
There's no update.log, neither on ~/gogs/log or /var/log, should i enable some option in the config then restart the service?
It's the default configuration from the provided Raspbian binaries, on prod level

**Comment by Unknwon** [comment]
When you test, are you pushing with real changes or just keep pushing `up-to-date`?

**Comment by usagirei** [comment]
Pushed a few changes to the README.md with new content on each commit:

* updated over SSH, no webui
* updated over HTTP, created web ui
* updated again over SSH with new content, file content does get refreshed  on WebUI, commits show on the commits tab and on the commit column
* added new file and pushed over SSH, file gets listed on WebUI, as expected,

none of the SSH commits show up on the dashboard however

**Comment by Unknwon** [comment]
@usagirei How you done this? https://github.com/gogits/gogs/issues/1864#issuecomment-152756107

**Comment by usagirei** [comment]
If you're asking if i did ran those commands, yes, i did, one of the first things i tried when i found the existing issue

**Comment by Unknwon** [comment]
@usagirei what is your system shell type, `sh`, or `bash`?

**Comment by usagirei** [comment]
the git user shell defaults to bash, let me change to the default shell and try it

**Comment by usagirei** [comment]
changed shell to /bin/sh, recreated the repo, pushed over ssh, and still no luck

**Comment by Unknwon** [comment]
Are you able to build from `develop` branch? Just pushed something to add more logs. (found a silent return)

**Comment by usagirei** [comment]
sure i'll give it a shot, still, will depend on how long it'll take to install all the stuff to be able to build the go sources

**Comment by Unknwon** [comment]
@usagirei http://dave.cheney.net/unofficial-arm-tarballs

**Comment by usagirei** [comment]
0.8.33.0210 on production runtime (should i run it under development?), same deal,

serv.log
2016/02/16 03:31:51 [T] No update task is presented: f86e9908-2c70-4d5a-abe0-a41e04fb7190
2016/02/16 03:32:29 [T] No update task is presented: c3adb264-c714-4abc-88e8-39abfcd7f185
2016/02/16 03:32:54 [T] No update task is presented: b9211cc3-35d2-4a42-a67d-134491e4557a

gogs.log
2016/02/16 03:23:41 [I] Run Mode: Production
2016/02/16 03:23:41 [I] First-time run install finished!
2016/02/16 03:24:26 [...routers/repo/repo.go:101 handleCreateError()] [E] CreatePost: initRepository: initRepository: path already exists: /mnt/usbdisk/GIT/usagirei/test-repo.git
2016/02/16 03:30:40 [I] Log Mode: File(Info)
2016/02/16 03:30:40 [I] Cache Service Enabled
2016/02/16 03:30:40 [I] Session Service Enabled
2016/02/16 03:30:40 [I] Git Version: 1.7.10.4
2016/02/16 03:30:40 [I] SQLite3 Supported
2016/02/16 03:30:40 [I] Run Mode: Production
2016/02/16 03:30:40 [I] First-time run install finished!

still no update.log

on a side note, for the "...: path already exists: /mnt/usbdisk/GIT/usagirei/test-repo.git..." message, it deleted the test-repo folder when i tried to create a repo with another one already existing, this could cause some other issues...

**Comment by usagirei** [comment]
OK, build ok, now on develop branch (0.8.37.0215), and it now works under SSH (at least on dev runtime)

Update.log was now created, but is empty, even after a few pushes

Upon pushing over SSH, the console output for ./gogs web under development runtime does show:

2016/02/16 04:18:15 [D] Session ID: b25b52ce62a0a595
2016/02/16 04:18:15 [D] CSRF Token: _zlSZq4jAnp4y2Ja8ndrvgOBmdk6MTQ1NTYwMzQ5NTA3OTA5NjkzNA==
2016/02/16 04:18:15 [T] TriggerTask [1].(new request): master
2016/02/16 04:18:15 [T] DeliverHooks [1]: processing delivery hooks
[Macaron] Completed /usagirei/test-repo/tasks/trigger?branch=master&secret=8bd2425eb5429b000de93b5e061875d6 202 Accepted in 12.637242ms
2016/02/16 04:18:15 [T] AddTestPullRequestTask[head_repo_id: 1, head_branch: master]: finding pull requests
2016/02/16 04:18:15 [T] AddTestPullRequestTask[base_repo_id: 1, base_branch: master]: finding pull requests

**Comment by usagirei** [comment]
Woke up and made some more tests:

* Yesterday i had configured it to run under the default gogs-repositories directories, SSH push updates OK
* Today, i made a symlink to ~/git to a mounted drive, reconfigured the app.ini to use that directory, SSH Pushes won't update
* Removed the symlink and made it a standard directory, SSH Pushes work again
* Renamed git to git2, and created a symlink git -> git2, SSH Pushes work normally
* Reconfigured gogs to directly use /mnt/usbdisk/git as repositories root, SSH Pushes won't update

The issue may be related to making gogs use a mounted folder as its repository source
Hopefully these help solving the issue

**Comment by Unknwon** [comment]
@usagirei thanks for the great detail!

The problem looks like is the `symlink` thing?

**Comment by usagirei** [comment]
As far as my testing went, issue is not exactly with symlinks, since a local symlink works, but mount points won't neither with symlinks nor with direct path

**Comment by Unknwon** [comment]
OK, `symlink with mount` maybe?

Or just `mount` isn't working as well?

**Comment by usagirei** [comment]
simply having the repositories root inside a mount point will make SSH pushes not work

**Comment by Unknwon** [comment]
@usagirei thanks!

Finally we found the problem?

**Comment by usagirei** [comment]
If more people could confirm by trying to set the root inside a mount, i'd say it is. 
Then all we'd need is to find a solution, mount points are rather important on an embedded system with limited storage like the PI

**Comment by Unknwon** [comment]
Somebody has noticed that Go has problem with finding right files for NAS (put repositories on NAS, pretty much same as your case, which put repositories on mount). Maybe it is the same thing in terms of some low level?

**Comment by usagirei** [comment]
Chances are, if they were on a unix based system, they were using mount points (i do the same for another mount point for downloading stuff over the PI), so i'd argue its probably that.

**Comment by Unknwon** [comment]
@usagirei Would you mind post the `mount` problem in [this thread](https://github.com/gogits/gogs/issues/2550) in a comment?

**Comment by Unknwon** [comment]
Whoever follows this thread, please refer to solution provided on [this comment](https://github.com/gogits/gogs/issues/2662#issuecomment-186614078) see if solves your problem.

**Comment by Raptord** [comment]
Hi, I'm having this issue as well, after installing Gogs on a new SUSE 11 SP3 virtual machine. We already had an install of Gogs on a Windows server, and I'm in the process of migrating the Windows install to the new SUSE one.

Pushing via SSH to the repositories that were transferred from the Windows install doesn't work, however if I create a new repo on the SUSE server, then I can use SSH normally. Pushing with HTTP works both for the old repos that were transferred and for new repos that I create on the SUSE server. SSH still doesn't update the dashboard after a successful HTTP push.

Not using any mounts, so the solution of disabling nosuid and noexec doesn't seem to apply to me. 

I tried "Rewrite '.ssh/authorized_keys' file" and "Rewrite all update hook of repositories" from the admin panel as was suggested elsewhere, but it hasn't helped.

**Comment by Unknwon** [comment]
Hi @Raptord ,

> Pushing via SSH to the repositories that were transferred from the Windows install doesn't work

What is the error?

What do you get when you do `ssh -T <domain>` on Windows machine?

**Comment by Raptord** [comment]
There is no error - the push itself works, however the dashboard doesn't update to show that a new push was made. In the serv.log file, I also get entries like this, like another poster above was getting:

![image](https://cloud.githubusercontent.com/assets/2872199/15114713/35841c9a-15c9-11e6-817e-f7f20285a592.png)

This is what I get when I run ssh -T <host> from my Windows machine to the linux host running Gogs:

![ssh](https://cloud.githubusercontent.com/assets/2872199/15114613/bcb53d1c-15c8-11e6-9a95-08754b21d8ed.png)

**Comment by Unknwon** [comment]
@Raptord are you using SQLite3?

**Comment by Raptord** [comment]
@Unknwon Yes, I am. Sorry, should have mentioned that earlier probably.

**Comment by Unknwon** [comment]
@Raptord try to use absolute path for the database path.

**Comment by Raptord** [comment]
@Unknwon I added the absolute path for the DB, and did another push through SSH. The dashboard did not update and I got more "No update task is presented" lines in the server log.

**Comment by Unknwon** [comment]
@Raptord what is your Goga binary location and what is the path show in your `.ssh/authorized_keys` file?

**Comment by Raptord** [comment]
@Unknwon My binary is in /home/sysdev/go/src/github.com/gogits/gogs.

I can't find the .ssh/authorized_keys file, where is it supposed to be on linux?

**Comment by Unknwon** [comment]
@Raptord `~/.ssh/authorized_keys`.

**Comment by Raptord** [comment]
@Unknwon There's no such file or directory. If it didn't exist though, wouldn't I be completely unable to push through SSH to the server?

I went to the admin panel and ran "Rewrite '.ssh/authorized_keys' file" to be sure, still no dice.

**Comment by Unknwon** [comment]
@Raptord Gogs is running on Windows or what?

**Comment by Raptord** [comment]
@Unknwon First we had a Gogs running on Windows. We want to transfer it to Linux (SUSE 11). The one on Windows works fine. The one on Linux is having the SSH problem I'm talking about. When I moved the Gogs data to the new Linux install I copied the config file (which I modified to work on the Linux version) and the 'data' and 'repositories' directories. Is there something else I missed for SSH?

**Comment by Unknwon** [comment]
@Raptord If it's running Linux and you do not have `~/.ssh/authorized_keys`, how is it possible you can connect to the SSH server?

**Comment by Raptord** [comment]
@Unknwon Beats me... Like I said, I'm able to push and pull, and the files are updated when I check the repo on Gogs, it's jsut the dashboard that doesn't update.

Is it possible that it's not checking ssh keys at all and just accepting any ssh connection?

**Comment by Unknwon** [comment]
@Raptord what is the SSH URL you use to push/pull?

**Comment by Raptord** [comment]
@Unknwon ssh://git@<host>:2222/<projectName>.git

**Comment by Unknwon** [comment]
@Raptord are you using builtin SSH server?

**Comment by Raptord** [comment]
@Unknwon Yes I am

**Comment by Unknwon** [comment]
@Raptord Any logs in `path/to/gogs/log/update.log`?

**Comment by Raptord** [comment]
@Unknwon Nope, it's empty

**Comment by grunmin** [comment]
Same question or even worse. When I first push my code to an empty repo with ssh, the gogs service shutdown and  even system halt for a while. As a comparison, that I push to an empty repo with https or I push to a repo which first init by https with ssh work fine. 
There is something in log file
```
2016/05/26 22:40:53 [I] Log Mode: File(Info)
2016/05/26 22:40:53 [I] Cache Service Enabled
2016/05/26 22:40:53 [I] Session Service Enabled
2016/05/26 22:40:53 [I] Git Version: 1.7.1
2016/05/26 22:40:53 [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: dial tcp [::1]:3306: getsockopt: connection refused
```
