### ISSUE TITLE
Wiki link problem

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#2080]
After creating a few pages on the wiki, linking seems to have the wrong base url

e.g. `[home](Home)` links to `org/project/Home` instead of `org/project/wiki/Home`

Is this actually intentional (which makes sense if it is so project files can be linked) or accidental?

**Comment by Unknwon** [comment]
Thanks your feedback!

I think use repository home URL as base URL is much more useful than wiki URL.

**Comment by ChangePlaces** [comment]
I agree, I'll close this!

**Comment by Unknwon** [comment]
:wink:

**Comment by maxhq** [comment]
If the Wiki is seen as part of the repo, setting the base URL to the repo seems OK.

But to comply with *All the Wikis in the world* (tm) it should be easier to point to another Wiki page. The need to prepend each link with `wiki/` (and to specify the link title again) is not very convenient.

Is it possible to implement the classic `[[Wiki-Page]]` style links?

**Comment by Unknwon** [comment]
> Is it possible to implement the classic [[Wiki-Page]] style links?

What does this mean?

**Comment by maxhq** [comment]
It means to link to another Wiki page by just specifying its name. This is the basic feature and idea of Wikis.

Basically the translation would be:
```
[[MyPage]]          - <a href="http://x.x.x.x/project/wiki/MyPage">MyPage</a>
[[MyPage|the page]] - <a href="http://x.x.x.x/project/wiki/MyPage">the page</a>
```
For more info see e.g. *Internal link* and *Piped link* at https://www.mediawiki.org/wiki/Help:Links#Internal_links.

**Comment by Unknwon** [comment]
@maxhq thanks, doesn't look like Markdown syntax but I get the idea.

**Comment by sfkleach** [comment]
+1, this is pretty basic to the idea of a wiki

**Comment by STALKER2010** [comment]
Implemented this Markdown extension in my local Git repo, along with Wiki sidebar (as on GitHub). Will send PR in a few days.
But the caveat is that GitHub has different ```[[...]]``` syntax. It is ```name|link```, not ```link|name``` as in MediaWiki. I've implemented GitHub one to match my PR related to wiki mirroring.

**Comment by Unknwon** [comment]
@pgimeno agree.

**Comment by mbound** [comment]
I have the same problem and I agree with @pgimeno suggestion. The current behaviour of linking to the base repo URL is inconsistent with the wiki being a separate URL vs the main repo, and is also inconsistent with how GitHub handles it. Hence mirrored repositories will also have all their wiki links broken.

**Comment by NeiroNx** [comment]
I am use gogs for mirroring my GitHUB repos, because it can die anytime.
And [[name|link]] still not working? And _Sidebar displaying?
We still waiting that function - i has seen code. It is no hard to add.
