### ISSUE TITLE
Changing username for non-local users allows duplicate registration

### ISSUE THREAD

**Issue by janh** [gogits/gogs#2154]
When a non-local user changes his username in Gogs, the user can still log in using their original username and password which will auto-registrate a new account. The original account is still accessible using the changed username. This means that there are now multiple accounts for the same user.

In my opinion, the best solution would be to disallow changing the username for non-local users, because it will always lead to confusion (user may expect that username is changed globally).

**Comment by Unknwon** [comment]
Hi, I just pushed fix to `develop` branch, please help test again!

**Comment by janh** [comment]
Now I get the message "Name cannot be empty." when changing the profile. This is because Chrome does not send the content of the disabled field.

When I modify the field using developer tools (remove "disabled" attribute), I can save the profile. However, then I can also modify the username.

I think the proper solution is to check if the user is non-local on the server. In that case keep the old username on the server.

**Comment by Unknwon** [comment]
Pushed to `develop` again :sweat_smile:

**Comment by janh** [comment]
The profile can now be saved.

But I still have a suggestion: Use `len(newName) == 0 || !ctx.User.IsLocal()` as condition in line 43 in *routers/user/setting.go*. Otherwise the user could still be renamed.

**Comment by Unknwon** [comment]
`!ctx.User.IsLocal()` this will allow rename to empty username, which we never want.

**Comment by janh** [comment]
That's why my suggestion contains both conditions. If either the name is empty or the user is local, the name won't be changed.

**Comment by Unknwon** [comment]
OK... The actual conditions should be reversed.

**Comment by Unknwon** [comment]
Please check out again!

**Comment by Unknwon** [comment]
Close as fixed.
