### ISSUE TITLE
Convert new repo filename to lowercase

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#2469]
When creating a new repo, should the filename be converted to lowercase, e.g. a new repo with title "FooBar", could become "foobar.git" - it's easier to type, and a nice way of making repo names constant.

**Comment by drsect0r** [comment]
Why? Both GitHub and GitLab don't have this behaviour. I think it best to let the people decide if they want to use repository names with upper, lower or mixed case?

**Comment by vtolstov** [comment]
2016-01-25 14:05 GMT+03:00 Jorrit Klein Bramel <notifications@github.com>:

> Why? Both GitHub and GitLab don't have this behaviour. I think it best to
> let the people decide if they want to use repository names with upper,
> lower or mixed case?
>
>
Internally github uses lowercase as i see? Why we need this feature?


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by ChangePlaces** [comment]
It's impossible to set a filename when creating a repo, so to create a repo of lowercase, your title must be lowercase. I think converting to lowercase will be good because of case-inconsistent OS's that don't care for caps.

**Comment by vtolstov** [comment]
@ChangePlaces i think you right +1 for this

**Comment by Unknwon** [comment]
I don't understand this issue?

All repositories' directories are converted to lowercase on file system.

**Comment by ChangePlaces** [comment]
I updated to 0.8.1 the other day, created a repo called FooBar, and I have to push to FooBar.git

**Comment by bkcsoft** [comment]
cloning derp/FooBaz with `http://example.com/derp/foobaz.git` works just fine, though the WebUI says `http://example.com/derp/FooBaz.git` so if anything it's a UI-bug, not a system-bug

**Comment by ChangePlaces** [comment]
what os are you using for client, and git server?

**Comment by bkcsoft** [comment]
Linux/Arch for client and Linux/Debian for server. I can test more
combinations if you want, though I don't think that the result will change
:)

**Comment by Unknwon** [comment]
> I updated to 0.8.1 the other day, created a repo called FooBar, and I have to push to FooBar.git

It might be a bug with SSH push in 0.8.1, but I'm sure it is fixed in recent versions.

**Comment by ChangePlaces** [comment]
Interesting, I'll have a play and report back!

**Comment by Unknwon** [comment]
ping @ChangePlaces

**Comment by ChangePlaces** [comment]
sorry, i haven't had time to update and check this out due to personal life. i've penciled it in for the weekend

**Comment by vilinski** [comment]
- created new repo withon Organization with RepoName
- gogs currently creates the file structure like  `gogs-repositories/organization/reponame.git`, which is ok. 
- But UI still shows `..Organization/RepoName.git`. 
- If click "copy to clipboard" and try to clone with e.g. SourceTree, i become "not a git repository" message.
- changing to lowercase - clone successful.

Can it be fixed or configured somehow?

**Comment by linquize** [comment]
This feature should be optional.

**Comment by Unknwon** [comment]
@vilinski what is your Gogs version? That should only happen in old versions.

@linquize it is the problem about the consistency of finding repository on the file system, not a feature that we can provide options.

**Comment by vilinski** [comment]
@Unknwon the latest binary version 0.8.25, downloaded from [here](https://dl.gogs.io/gogs_v0.8.25_linux_386.tar.gz)
and yes, currently i can use only absolute path like /git/home/gogs-repositories/OrgName/RepoName.git instead of just orgname/reponame.git. Can't actually solve it using proper ssh key

**Comment by Unknwon** [comment]
@vilinski you are not allowed to both login shell and use SSH for clone git repositories for same `system user`. That's why you need full path.

**Comment by Unknwon** [comment]
Close due to lack of feedback.
