### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by Wikunia** [gogits/gogs#3987]
I am using the gogs api but get a 
`Access-Control-Allow-Origin` error. Is it possible to allow it inside the api?

- Gogs version (or commit ref): 0.9.99
- Git version: 1.9.1
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

**Comment by Unknwon** [comment]
Example?

**Comment by Wikunia** [comment]
I get the error:

```
XMLHttpRequest cannot load http://xxx.xxx.xxx.xxx:3000/api/v1/repos/xxx/xxx/issues?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access
```

And doing stuff like

```
        var request = $.ajax({
            url: apiUrl+'repos/xxx/xxx/issues?token='+token,
            method: "GET",
            dataType: "json",
            crossDomain: true,
        });
```

**Comment by Unknwon** [comment]
Where did you put this code? Inject JS in HTML does not seem to be a good idea...

**Comment by Wikunia** [comment]
It's part of a `JS` script but really that doesn't have anything to do with the issue.

**Comment by Unknwon** [comment]
>but really that doesn't have anything to do with the issue.

I don't understand what does this mean?

**Comment by Wikunia** [comment]
It's a common problem that the server restricts the access from other servers (hier my gogs server restricts the access from localhost). It doesn't matter if I do the request using php,js,perl,python or whatever. It's just that Chrome blocks it because Chrome sees that the server doesn't like it. I would like to allow it inside a gogs setting.

**Comment by Unknwon** [comment]
I don't think this error message is from Gogs.

**Comment by Wikunia** [comment]
In general the gogs script needs a `Access-Control-Allow-Origin` header. But I don't know enough about gogs to add it to the api.

**Comment by Unknwon** [comment]
Oh, I see, so you want a setting to set custom `Access-Control-Allow-Origin` header?

**Comment by Wikunia** [comment]
Si :) I would like to allow some or all domains to access the api.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch. See https://github.com/gogits/gogs/commit/5e01ecbc0528488427ee455578acbe7ff92efcfe in detail.

**Comment by girishso** [comment]
I am still running into this issue, with error

```
XMLHttpRequest cannot load http://localhost:3000/api/v1/user/repos. Response to preflight request doesn't pass access control
```

Server logs show

```
[Macaron] 2017-03-09 10:25:12: Started OPTIONS /api/v1/user/repos for [::1]
[Macaron] 2017-03-09 10:25:12: Completed OPTIONS /api/v1/user/repos 404 Not Found in 1.502769ms
```

Looks we need to handle preflight OPTIONS request in router (unless I am missing something). 

Using https://github.com/rs/cors seems like a good option to me.

**Comment by Unknwon** [comment]
AFAIK, Gogs does not have any routes registered with `OPTIONS` method. And I don't know why that is needed.

**Comment by girishso** [comment]
I am using following to access API from other domain

```javascript
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("GET", "http://localhost:3000/api/v1/user/repos");
xhr.setRequestHeader("authorization", "token XYZ");
xhr.setRequestHeader("content-type", "application/json");

xhr.send();
```

**Comment by girishso** [comment]
Here is some dope for you!

- Javascript Application initiates a XHR Request
- Browser intercepts request and sends the web server a “Preflight” request
Preflight consists of sending an OPTIONS request to the resource with “Origin” header set, and optionally other useful headers about the request which is to come, such as the Request Method and potential Request Headers
- Server replies with the “Appropriate” response headers to the OPTIONS call stipulating what the browser should allow.
- Browser gets the results of the Preflight and decides if the XHR Request should be allowed.
- Browser sends the request, or doesn’t

https://husobee.github.io/golang/cors/2015/09/26/cors.html

**Comment by Unknwon** [comment]
@girishso thanks for the info! Does GitHub support such `OPTIONS`? If yes, any references or proves?

**Comment by girishso** [comment]
@Unknwon try running following in development console of browser, you will see that it makes a OPTIONS request first (keep in mind Github allows caching of the OPTIONS request for 24 hours)

```
var data = null;

var xhr = new XMLHttpRequest();

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("GET", "https://api.github.com/users/girishso");

xhr.send(data);
```

**Comment by girishso** [comment]
Fixed in PR: https://github.com/gogits/gogs/pull/4264

**Comment by lorisp1** [comment]
Hello,
I am trying to make Gogs return Access-Control-Allow-Origin: * header, so I configured custom/conf/app.ini as per https://gogs.io/docs/advanced/configuration_cheat_sheet adding the following section:

```
[http]
ACCESS_CONTROL_ALLOW_ORIGIN = *
```
I restarted the service and I noticed that the header is still missing.

Looking at [setting.go](https://github.com/girishso/gogs/blob/master/modules/setting/setting.go), it seems that the setting HTTP.AccessControlAllowOrigin is not being loaded from ini files.

Any suggestions?
Thanks.

**Comment by girishso** [comment]
https://github.com/gogits/gogs/blob/master/pkg/context/context.go#L266 It's reading the settings.  

> Looking at setting.go, it seems that the setting HTTP.AccessControlAllowOrigin is not being loaded from ini files.

You may be right, looks like some regression issue.

**Comment by lorisp1** [comment]
Do you have information about when the fix will be available, or a workaround?

**Comment by Unknwon** [comment]
@lorisp1 it is possible that you changed wrong configuration file...

**Comment by lorisp1** [comment]
@Unknwon I added the setting in custom/conf/app.ini
Can you confirm that the parameter is being read from the file, despite the function NewContext in [setting.go](https://github.com/girishso/gogs/blob/master/modules/setting/setting.go) doesn't seem to do it?

**Comment by Unknwon** [comment]
Added:

![image](https://user-images.githubusercontent.com/2946214/32922590-ec28f8ba-cb00-11e7-8e98-c1d1d4d6ff1a.png)
